"""empty message

Revision ID: 1478401664a1
Revises: None
Create Date: 2015-05-16 17:57:47.939428

"""

# revision identifiers, used by Alembic.
revision = '1478401664a1'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
