"""empty message

Revision ID: 3ceaf63bbb36
Revises: None
Create Date: 2015-05-14 11:18:03.543997

"""

# revision identifiers, used by Alembic.
revision = '3ceaf63bbb36'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pila',
    sa.Column('idPila', sa.Integer(), nullable=False),
    sa.Column('nomProducto', sa.String(length=30), nullable=True),
    sa.Column('idActor', sa.Integer(), nullable=True),
    sa.Column('nomActor', sa.String(length=150), nullable=True),
    sa.Column('idObjetivo', sa.Integer(), nullable=True),
    sa.Column('descripObjetivo', sa.String(length=150), nullable=True),
    sa.Column('idAccion', sa.Integer(), nullable=True),
    sa.Column('descripAccion', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('idPila')
    )
    op.drop_table(u'user')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(u'user',
    sa.Column(u'fullname', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column(u'username', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column(u'password', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column(u'email', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint(u'username', name=u'user_pkey')
    )
    op.drop_table('pila')
    ### end Alembic commands ###
