"""empty message

Revision ID: 41a225c7ebf2
Revises: 3ceaf63bbb36
Create Date: 2015-05-14 16:06:27.949637

"""

# revision identifiers, used by Alembic.
revision = '41a225c7ebf2'
down_revision = '3ceaf63bbb36'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actores',
    sa.Column('id_actores', sa.Integer(), nullable=False),
    sa.Column('nombre_actores', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_actores')
    )
    op.create_table('objetivos',
    sa.Column('id_objetivos', sa.Integer(), nullable=False),
    sa.Column('descripObjetivos', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id_objetivos')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('objetivos')
    op.drop_table('actores')
    ### end Alembic commands ###
